/*
 * Stoatworks Labs - About window data for plumbicon.
 *
 * PROVISIONAL HAND COPY. Across the fleet this file is GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json,
 * which is the one place these facts are written down. plumbicon is not
 * registered there yet, so this copy was adapted by hand from a sibling's
 * generated header - exactly as graticule's was. Register the project and
 * re-run the sync; do not hand-edit it after that.
 *
 * `guide` is deliberately empty: no user guide exists, and the About block
 * leaves out a button whose link would 404 rather than showing one.
 *
 * `version` here is a fallback. The build injects the real one and overrides
 * it.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "plumbicon";
    inline constexpr auto slug = "plumbicon";
    inline constexpr auto hook = "A tube camera for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/plumbicon/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/plumbicon";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
